# Site settings
title: System76 Docs
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Official System76 documentation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.system76.com" # the base hostname & protocol for your site

collections:
  articles:
    output: true

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM # Use GitHub markdown extensions

gems:
  - jekyll-redirect-from
